// src/pages/article.svelte
<article class="article">
  {#if loading}
    <Loading full={true} move={true}/>
  {:else if empty}
    <div class="article__empty">
      <Error status={204} message="no article"/>
    </div>
  {:else}
    <div class="article__wrap">
      <header class="article__header">
        <h1>{title === '.' ? 'Untitled work' : title}</h1>
        {#if headDescription?.length > 0}
          <p>
            {#each headDescription as label}
              <span>{label}</span>
            {/each}
          </p>
        {/if}
      </header>
      <div class="article__body">
        <ContentBody
          body={_contentBody}
          on:openLightbox={onOpenLightbox}/>
      </div>
      <nav class="article__star">
        <StarButton
          count={starButton.count}
          disabled={starButton.disabled}
          on:click={onClickStar}/>
      </nav>
    </div>
    {#if comments?.length > 0}
      <article class="comments">
        <h1 class="comments__title">Comments</h1>
        <ul class="comments__index">
          {#each comments as o, key}
            <Comment
              srl={o.srl}
              content={o.content}
              date={o.date}/>
          {/each}
        </ul>
      </article>
    {/if}
  {/if}
</article>
{#if lightbox?.src}
  <LightBox
    {...lightbox}
    on:close={onCloseLightbox}/>
{/if}

<script>
import { onMount } from 'svelte'
import { ofetch } from 'ofetch'
import { error } from '../store'
import { hashScroll } from '../libs/util'
import Loading from '../components/loading/loading-page.svelte'
import Error from '../components/error.svelte'
import StarButton from '../components/pages/article/star-button.svelte'
import ContentBody from '../components/pages/article/content-body.svelte'
import LightBox from '../components/pages/article/lightbox.svelte'
import Comment from '../components/pages/article/comment.svelte'

export let route
let loading = true
let srl
let title
let headDescription
let contentBody
let starButton = {
  disabled: false,
  count: 0,
}
let comments = []
let empty = false
let lightbox = {}

$: _contentBody = contentBody

async function fetchData()
{
  try
  {
    loading = true
    let res = await ofetch(`/api/article/${route.params.article}/`, {
      responseType: 'json',
    })
    srl = res.srl
    title = res.title
    headDescription = [
      res.nestName && `Nest: ${res.nestName}`,
      res.categoryName && `Category: ${res.categoryName}`,
      res.date && `Date: ${res.date}`,
    ].filter(Boolean)
    contentBody = res.content
    starButton.disabled = !res.enableStarButton
    starButton.count = res.star
    comments = res.comments
    loading = false
    // move scroll
    hashScroll(location.hash)
  }
  catch (e)
  {
    const status = e.response?._data?.status || 500
    const message = e.response?._data?.message || 'Unknown error'
    if (status === 404)
    {
      empty = true
    }
    else
    {
      error.update(() => ({ status, message }))
    }
    loading = false
  }
}

async function onClickStar()
{
  try
  {
    let res = await ofetch(`/api/article/${route.params.article}/star/`, {
      method: 'post',
      responseType: 'json',
    })
    starButton.disabled = true
    starButton.count = Number(res.star)
    if (!res.success) throw new Error(res.message)
  }
  catch (e)
  {
    alert('Failed update star')
  }
}

function onOpenLightbox({ detail: { src, srcDark, alt } })
{
  lightbox.src = src
  lightbox.srcDark = srcDark
  lightbox.alt = alt
}

function onCloseLightbox()
{
  lightbox.src = undefined
  lightbox.srcDark = undefined
  lightbox.alt = undefined
}

onMount(() => fetchData().then())
</script>

<style lang="scss">
@import './article';
</style>

// client/pages/article/index.vue
<template>
<article class="article">
  <Loading v-if="state.loading"/>
  <template v-else-if="state.article">
    <header class="article-header">
      <h1>{{_title}}</h1>
      <p>
        <span v-for="o in _description">{{o}}</span>
      </p>
    </header>
    <div class="article-body">
      <ContentBody
        :content="state.article.content"
        @click:image="onClickImage"/>
    </div>
    <nav class="article-star">
      <StarButton
        :count="state.article.star.count"
        :disabled="state.article.star.disabled"
        @click:button="onClickStar"/>
    </nav>
    <Comments
      v-if="state.comment"
      :total="state.comment.total"
      :index="state.comment.index"
      class="article-comment"
      @open:image="onClickImage"/>
  </template>
  <Error
    v-else
    page-title="No Content"
    :error="new ServiceError('No Content', 204)"
    class="article-empty"/>
  <teleport to="#modal">
    <Lightbox
      :src="state.lightbox?.src"
      :src-dark="state.lightbox?.srcDark"
      :alt="state.lightbox?.alt"
      @close="onCloseLightbox"/>
  </teleport>
</article>
</template>

<script setup>
import { reactive, computed, onMounted, nextTick } from 'vue'
import { useRoute } from 'vue-router'
import { ofetch } from 'ofetch'
import ServiceError from '../../libs/error.js'
import { hashScroll } from '../../libs/util.js'
import { dateFormat } from '../../libs/strings.js'
import Loading from '../../components/etc/loading.vue'
import Error from '../../components/content/error.vue'
import ContentBody from '../../components/article/content-body.vue'
import StarButton from '../../components/article/star-button.vue'
import Comments from '../../components/article/comments.vue'
import Lightbox from '../../components/article/lightbox.vue'

const route = useRoute()
const state = reactive({
  loading: true,
  article: null,
  comment: null,
  lightbox: null, // { src, srcDark, alt }
})

const _title = computed(() => {
  if (state.article?.title === '.') return 'Untitled Work'
  return state.article?.title || ''
})
const _description = computed(() => {
  const date = state.article?.regdate
    ? dateFormat(new Date(state.article.regdate), '{yyyy}-{MM}-{dd}')
    : null
  return [ ...(state.article?.description || []), date ].filter(Boolean)
})

onMounted(async () => {
  try
  {
    state.loading = true
    const res = await ofetch(`/api/article/${route.params.srl}/`)
    if (!res?.data) throw new ServiceError('No Content', 204)
    state.article = {
      srl: res.data.srl,
      title: res.data.title,
      description: [ res.data.nestName, res.data.categoryName ].filter(Boolean),
      content: res.data.content,
      regdate: res.data.regdate,
      star: {
        count: res.data.star,
        disabled: res.data.usedUpStar,
      },
    }
    state.comment = res.data.comment
    // scroll to hash content
    if (location.hash)
    {
      await nextTick()
      hashScroll(location.hash)
    }
  }
  catch (_e)
  {
    if (_e instanceof ServiceError)
    {
      if (_e.code !== 204) throw _e
    }
    else
    {
      throw new ServiceError(_e?.message)
    }
  }
  finally
  {
    state.loading = false
  }
})

function onClickImage({ src, srcDark, alt })
{
  state.lightbox = { src, srcDark, alt }
}

function onCloseLightbox()
{
  state.lightbox = null
}

async function onClickStar()
{
  if (!state.article?.star) return
  try
  {
    await ofetch(`/api/article/${route.params.srl}/star/`, {
      method: 'post',
    })
    state.article.star.disabled = true
    state.article.star.count += 1
  }
  catch (_e)
  {
    alert('Failed update star.')
  }
}
</script>

<style src="./index.scss" lang="scss" scoped></style>
